#!/bin/bash

wget -c https://github.com/2mesistemas/vaivendo/raw/master/cshell_install.sh
chmod +x cshell_install.sh 
sudo ./cshell_install.sh
wget https://github.com/2mesistemas/vaivendo/raw/master/CSHELL.zip
wget https://github.com/2mesistemas/vaivendo/raw/master/cshell.zip
chmod +x /usr/bin/cshell/vpn
sudo rm -R /tmp/CSHELL
sudo rm -R /usr/bin/cshell
unzip CSHELL.zip
unzip cshell.zip
sudo cp -R cshell /usr/bin/
sudo rm -R cshell
sudo rm cshell.zip
sudo rm CSHELL.zip
