#!/bin/bash
# Stalker WM Portal Ministra road warrior installer for Debian, Ubuntu

# This script will work on Debian, Ubuntu and probably other distros
# of the same families, although no support is offered for them. It isn't
# bulletproof but it will probably work if you simply want to setup a Stalker WM Portal on
# your Debian/Ubuntu box. It has been designed to be as unobtrusive and
# universal as possible.

# This is a free shell script under GNU GPL version 3.0 or above
# Copyright (C) 2017 LinuxHelps project.
# Feedback/comment/suggestions : https://linuxhelps.net/
# Author Ivan Bachvarov a.k.a SlaSerX


# Color schema

red='\033[01;31m'
blue='\033[01;34m'
green='\033[01;32m'
norm='\033[00m'

# Temporary colors
RED="$(tput setaf 1)"
YELLOW="$(tput setaf 3)"
CYAN="$(tput setaf 6)"
NORMAL="$(tput sgr0)"

# smallLoader colors

CSI="\033["
CEND="${CSI}0m"
CRED="${CSI}1;31m"
CGREEN="${CSI}1;32m"
CYELLOW="${CSI}1;33m"
CPURPLE="${CSI}1;35m"
CCYAN="${CSI}1;36m"
CBROWN="${CSI}0;33m"

# smallLoader

smallLoader() {
    echo ""
    echo ""
    echo -ne '[ + + +             ] 3s \r'
    sleep 1
    echo -ne '[ + + + + + +       ] 2s \r'
    sleep 1
    echo -ne '[ + + + + + + + + + ] 1s \r'
    sleep 1
    echo -ne '[ + + + + + + + + + ] Press [Enter] to continue... \r'
    echo -ne '\n'

    read -r
}



VER="5.6.6"
PRODUCT="Ministra Portal"
WEB="http://`ip route get 8.8.8.8 | awk '{print $NF; exit}'`/stalker_portal"
WAN="`wget -q -O - http://icanhazip.com/ | tail`"
LOCAL="`ip route get 8.8.8.8 | awk '{print $NF; exit}'`"

supported="    Debian 8, 9 on i386 and amd64
               Ubuntu 16.04"

skipyesno=0

# Ask a yes or no question
# if $skipyesno is 1, always Y
# if NONINTERACTIVE environment variable is 1, always Y
yesno () {
  # XXX skipyesno is a global set in the calling script
  # shellcheck disable=SC2154
  if [ "$skipyesno" = "1" ]; then
    return 0
  fi
  if [ "$NONINTERACTIVE" = "1" ]; then
    return 0
  fi
  while read -r line; do
    case $line in
      y|Y|Yes|YES|yes|yES|yEs|YeS|yeS) return 0
      ;;
      n|N|No|NO|no|nO) return 1
      ;;
      *)
      printf "\n${YELLOW}Please enter ${CYAN}[y]${YELLOW} or ${CYAN}[n]${YELLOW}:${NORMAL} "
      ;;
    esac
  done
}

install_msg() {
cat <<EOF

  Welcome to the ${RED}$PRODUCT${NORMAL} installer, version ${RED}$VER${NORMAL}

  This script must be run on a freshly installed supported OS. It does not
  perform updates or upgrades (use your system package manager).

  The systems currently supported by install.sh are:

EOF
echo "${CYAN}$supported${NORMAL}"
cat <<EOF

  If your OS/version/arch is not listed, installation ${RED}will fail${NORMAL}. More
  details about the systems supported by the script can be found here:

    ${UNDERLINE}${CYAN}https://github.com/SlaSerX/stalker/blob/master/docs/os-suport${NORMAL}


EOF

  printf " Continue? (y/n) "
  if ! yesno; then
    exit
  fi
}

if [ "$skipyesno" -ne 1 ] && [ -z "$setup_only" ]; then
  install_msg
fi

# Ajustar o Horário
echo "America/Sao_Paulo" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata
udo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
sudo hwclock --systohc

# Install Necessary services & packets
#apt-get -y -u install unzip nginx memcached php php-mcrypt php-mysql php-pear nodejs libapache2-mod-php
apt-get install zip unzip -y
apt install software-properties-common & add-apt-repository ppa:ondrej/php 
apt update & apt upgrade -y 
apt remove php* -y 
sleep 1

# Install required packages
apt -y install apache2 nginx memcached curl mysql-server php7.0 php7.0-mysql php7.0-memcached  php7.0-curl php-pear php7.0-xml php7.0-mcrypt php7.0-zip php7.0-sqlite3 php7.0-imagick  php7.0-soap php7.0-intl php7.0-gettext php7.0-tidy php7.0-geoip nodejs systemd-sysv -y
sleep 1

# Set php7.0 as default PHP.
update-alternatives --set php /usr/bin/php7.0 
a2dismod php7.* 
a2enmod php7.0
systemctl restart apache2
sleep 1

# Apache & Nginx config
a2enmod rewrite
apt-get purge libapache2-mod-php5filter > /dev/null
phpenmod mcrypt
cd /etc/apache2/sites-enabled/
rm -rf *
wget https://download1581.mediafire.com/07k689nwxwog/te0pkbwehmelmea/default
cd /etc/apache2/
rm -rf ports.conf
wget https://download1486.mediafire.com/lzjgzii02kfg/n1wlsh1xm8o8s0g/ports.conf
cd /etc/nginx/sites-available/
rm -rf default
wget https://download1581.mediafire.com/07k689nwxwog/te0pkbwehmelmea/default
/etc/init.d/apache2 restart
/etc/init.d/nginx restart
sleep 1

apt-get update

sleep 1

# Pear
pear channel-discover pear.phing.info
pear install -Z phing/phing
sleep 1

# Install NPM  2.5.11
apt-get -y -u install npm
npm install -g npm@2.15.11
ln -s /usr/bin/nodejs /usr/bin/node

# Install MySQL Server in a Non-Interactive mode. Default root password will be "29084710"
echo "mysql-server mysql-server/root_password password $pass" | sudo debconf-set-selections
echo "mysql-server mysql-server/root_password_again password $pass" | sudo debconf-set-selections

apt-get install -y mysql-server > /dev/null

sed -i 's/127\.0\.0\.1/0\.0\.0\.0/g' /etc/mysql/my.cnf
mysql -uroot -p$pass -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root" AND `Host`="localhost"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; FLUSH PRIVILEGES;'

/etc/init.d/mysql restart

# Download Ministra
cd /var/www/html/
wget https://download1589.mediafire.com/mxyrblhcssyg/kb3y2di2l9oobpz/ministra-5.6.6.zip
unzip ministra-5.6.6.zip
rm -rf *.zip

# Create Database
mysql -uroot -p$pass -e "create database stalker_db"
mysql -uroot -p$pass -e "GRANT ALL PRIVILEGES ON stalker_db.* TO stalker@localhost IDENTIFIED BY '1' WITH GRANT OPTION;"

# MySQL Settings
echo 'sql_mode=""' >> /etc/mysql/mysql.conf.d/mysqld.cnf

/etc/init.d/mysql restart

# PHP Settings
echo "short_open_tag = On" >> /etc/php/7.0/apache2/php.ini

# Ministra Vendor bug Fix 
sleep 1
rm -rf /var/www/html/stalker_portal/admin/vendor
cd /var/www/html/stalker_portal/admin
wget https://download1490.mediafire.com/qu6ogk5v2qzg/0fi9cyzrilek2zv/vendor.tar
tar -xvf vendor.tar
sleep 1

# Phing :)
sudo apt update
sudo apt install phing -y
cd /var/www/html/stalker_portal/deploy
phing
sleep 1

echo ""
echo -e "${CCYAN}-----------------------------------------------------------------------${CEND}"
echo ""
echo -e "${CCYAN}[ Install Complete Default username is: ${CRED}admin${CEND} ${CCYAN}Default password is: ${CRED}1${CEND} ${CCYAN}: ]${CEND}"
echo ""
echo -e "IP WAN       : ${CGREEN}${WAN}${CEND}"
echo -e "Local IP     : ${CGREEN}${LOCAL}${CEND}"
echo -e "MySQL Pass   : ${CGREEN}${pass}${CEND}"
echo -e "WEB          : ${CGREEN}${WEB}${CEND}"
echo ""
echo -e "${CCYAN}-----------------------------------------------------------------------${CEND}"
echo ""

